language: java
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_deploy:
  - ./gradlew build
deploy:
  - provider: releases
    api_key:
      secure: "Qcw7FvnWxZDV9xw1rDbKj3B7dXxYKSxTOVLqMZPgTKxnU3hVrWykVnj3ipx2+hSHu1KbKw1Gd5DZVSccuEPeeJiGRwH8h2nLmo4WGAaVplhUmawuzwJhhwimxU+K8O1dywRMC7kERdVNRjeIga/hcFl/vum5+esWyrQS3KFoPGluG2QK75i2u4MrQ7d/J9VhQbp9vmZ3Q7NzZ8UnLDY7hTV2+LegVjpxh7Kzy8mG2wAgiKScv/hazcvUjIHUdXGKdtjYTIL0uGv3l+4o9Nmm7gZ8S1CHGVxmP0a+bQUxXf+7FpBztlQp7ocaw3wU+2FcaKeDf7C+L42mIJx2LeQ6eoHNIF1F7ldeg8O6KfrEPtj97ql/GUMx5XzFIborbYd+jTLo7NvmyDExBSR5EOc2kYbpic31+NZlWMjnDJQq/bcWZ9P0TASaeJvgA8h8OJWfEGNjptsf9u5KbDrLYjE8L9GjvJz4nFCHOY/gKmyB2nDFbiR/AQWLzfiuyBTRuSKQGk8CB3tQVSLU3Ax8RQlJz94DXy9pWl4jE/RtKyN1N96aOj8kKtANAPcl9g4Nfv81zf870UDbVh90q4PCnUUG2c9RuEzViZMclJSDc0+r4MV+JVeQA88yUzGJRRzsm3D9RGTFQ/+CoD3jfeoztm9fctKTE4ZmfPZtqyNJRSIpZdw="
    file: "dist/ontology.jar"
    skip_cleanup: true
    on:
      tags: true
